export enum EFormControlNames {
    NOMBRE = "nombre",
    APELLIDO_PATERNO = "apellidoPaterno",
    APELLIDO_MATERNO = "apellidoMaterno",
    FECHA_NACIMIENTO = "fechaNacimiento",
    SEXO = "sexo",
    CURP = "curp",
    TELEFONO = "telefono",
    ROL = "rol",
    TIPO_CUENTA = "tipoCuenta",
    RAZON_ALTA = "razonAlta",
    ROL_PASSWORD = "rolPassword",
    EMAIL = "email",
    PASSWORD = "password",
    NOTAS = "notas",
    DESCRIPCION = "descripcion",
    DURACION_SESION = "duracionPorSesion",
}